### ISSUE TITLE
Any ETA on the initial release of the plugin?

### ISSUE THREAD

**Issue by isle99** [tgrosinger/tq-obsidian#1]
I'm currently thinking moving to a new task management system in Obsidian, and I was wondering when this plugin might be coming out since I don't want to need to swap again later on.

Also, do you mind sharing some of the functionalities that the plugin might have?
I saw a lot of interesting things in the commits.

**Comment by tgrosinger** [comment]
@isle99, thanks for the interest. I think it's getting close to a point where it has enough of the planned functionality, but there are definitely some parts of the UI that are very rough. Maybe in a couple weeks, but not sure. I could upload a build here that you could install manually if you'd like. Let me know if that would be interesting.

I don't want to talk much about features since I'm currently just using it and adding features that I think are missing for my workflow. That's basically how I'm planning on progressing with this plugin. I'll put it in the community plugins for anyone that is interested, but features will likely be driving primarily by my workflow.

**Comment by rolfaalders** [comment]
I'm also very interested :) 
I get it that you want to drive features from your own workflow. 
It there a possibility that you share your workflow, so that we perhaps can see if there's a match, and/or can get inspired by your workflow?
Thanks

**Comment by isle99** [comment]
@tgrosinger "I could upload a build here that you could install manually if you'd like".

Yeah, that would be great. 👍

It would also be nice if you shared your workflow, like the other person mentioned, so that we could know what to expect from it in the future.

**Comment by tgrosinger** [comment]
I decided to just hide the pieces that were still too rough to release so I could get an initial version out the door.

I uploaded an initial release and submitted for addition to the community plugin list. Not too long now.
