### ISSUE TITLE
Add a "completion" date to tasks and enable filtering by that date

### ISSUE THREAD

**Issue by bzupnick** [tgrosinger/tq-obsidian#4]
**Is your feature request related to a problem? Please describe.**
I like to keep a running list of things I completed that day, but also, yesterday I "completed" something, to realize that it's not actually completed and I want to "uncheck" it. 

**Describe the solution you'd like**
So it'd be nice to be able to query for "recently completed tasks" to find the task and untick it, and also have a query for "tasks completed today" in my daily template.

**Describe alternatives you've considered**
Currently I can do a full vault search for the plaintext of the task, find it, then untick it.

**Comment by tgrosinger** [comment]
@bzupnick, thank you for the suggestion. A "recently completed" filter parameter sounds interesting, however I do not think it fits within my workflow and therefore will not be adding it at this point. 

One of the reasons I chose this format is because it makes the files easy to interact with from other plugins. You can probably put together something with the DataView plugin that shows tasks which are completed from files with a recent modified time.
